### ISSUE TITLE
The distance between each menu item

### ISSUE THREAD

**Issue by muhammedgunes** [BrotherV/ArcRayMenu#1]
How can i set distance between each menu item.

**Comment by BrotherV** [comment]
for which  one of menu you want to do?!!! for  ArcMenu or RayMenu?

**Comment by BrotherV** [comment]
if you want to change Arc Menu child distances, just increase MIN_RADIUS value in ArcLayout.java.
if you want to change Ray Menu child distances, just increase DEFAULT_CHILD_GAP value in RayLayout.java.

**Comment by muhammedgunes** [comment]
i want to change arcmenu clid distance. Thanks :)
