### ISSUE TITLE
Change the distance between the Menu button and the Menu items

### ISSUE THREAD

**Issue by AdrianVidaurre** [BrotherV/ArcRayMenu#2]
How to change the distance between the menu button and the menu items? My problem is that I want to use this library with 3 menu items but the distance is fine only while you have at least 5 menu items, if you have less than 5 menu items the distance becomes too short and the menu button overlaps with the menu items  Example:

![image](https://cloud.githubusercontent.com/assets/10786247/17250500/f9d54150-557a-11e6-9cf0-d5112201c248.png)

**Comment by BrotherV** [comment]
Hi, if you still have kind of problem, you should increase the MIN_RADIUS const in ArcLayout.java.
I chose 100 for default and it's work on every screen.

**Comment by AdrianVidaurre** [comment]
Excellent work, thank you very much!
